#!/usr/bin/env node

/**
 * DorkNexus Setup Wizard
 * Interactive setup for first-time users
 */

import readline from 'readline';
import { execSync, spawn } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ANSI color codes
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  dim: '\x1b[2m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  white: '\x1b[37m',
  bgBlue: '\x1b[44m',
  bgGreen: '\x1b[42m',
};

const c = colors;

// Utility functions
function print(text = '') {
  console.log(text);
}

function printColor(color, text) {
  console.log(`${color}${text}${c.reset}`);
}

function printStep(step, total, text) {
  console.log(`${c.cyan}[${step}/${total}]${c.reset} ${text}`);
}

function printSuccess(text) {
  console.log(`${c.green}✓${c.reset} ${text}`);
}

function printError(text) {
  console.log(`${c.red}✗${c.reset} ${text}`);
}

function printWarning(text) {
  console.log(`${c.yellow}⚠${c.reset} ${text}`);
}

function printBox(lines, color = c.cyan) {
  const maxLen = Math.max(...lines.map(l => l.length));
  const border = '═'.repeat(maxLen + 2);
  print(`${color}╔${border}╗${c.reset}`);
  lines.forEach(line => {
    const padding = ' '.repeat(maxLen - line.length);
    print(`${color}║${c.reset} ${line}${padding} ${color}║${c.reset}`);
  });
  print(`${color}╚${border}╝${c.reset}`);
}

function clearScreen() {
  console.clear();
}

// Create readline interface
function createPrompt() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

async function question(rl, prompt) {
  return new Promise(resolve => {
    rl.question(prompt, answer => {
      resolve(answer);
    });
  });
}

async function confirm(rl, prompt, defaultValue = true) {
  const suffix = defaultValue ? '[Y/n]' : '[y/N]';
  const answer = await question(rl, `${prompt} ${c.dim}${suffix}${c.reset} `);
  if (answer.trim() === '') return defaultValue;
  return answer.toLowerCase().startsWith('y');
}

// Check system requirements
function checkNodeVersion() {
  const version = process.version;
  const major = parseInt(version.slice(1).split('.')[0], 10);
  return { version, major, ok: major >= 18 };
}

function checkNpmInstalled() {
  try {
    const version = execSync('npm --version', { encoding: 'utf-8' }).trim();
    return { version, ok: true };
  } catch {
    return { version: null, ok: false };
  }
}

function checkDependenciesInstalled() {
  return fs.existsSync(path.join(__dirname, 'node_modules'));
}

function checkEnvConfigured() {
  const envPath = path.join(__dirname, '.env.local');
  if (!fs.existsSync(envPath)) return { exists: false, hasKey: false };

  const content = fs.readFileSync(envPath, 'utf-8');
  const hasKey = content.includes('GEMINI_API_KEY=') &&
                 !content.includes('GEMINI_API_KEY=your_') &&
                 !content.includes('GEMINI_API_KEY=\n') &&
                 !content.includes('GEMINI_API_KEY=\r');
  return { exists: true, hasKey };
}

// Installation functions
function installDependencies() {
  return new Promise((resolve, reject) => {
    print();
    printColor(c.dim, 'Running npm install...');
    print();

    const npmInstall = spawn('npm', ['install'], {
      cwd: __dirname,
      stdio: 'inherit',
      shell: true,
    });

    npmInstall.on('close', code => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`npm install failed with code ${code}`));
      }
    });

    npmInstall.on('error', reject);
  });
}

function createEnvFile(apiKey) {
  const envContent = `# DorkNexus Environment Configuration
# Generated by setup wizard

# Google Gemini API Key
GEMINI_API_KEY=${apiKey}
`;
  fs.writeFileSync(path.join(__dirname, '.env.local'), envContent);
}

function startDevServer() {
  print();
  printColor(c.cyan, 'Starting development server...');
  print();

  const devServer = spawn('npm', ['run', 'dev'], {
    cwd: __dirname,
    stdio: 'inherit',
    shell: true,
  });

  devServer.on('error', err => {
    printError(`Failed to start server: ${err.message}`);
  });
}

// Main wizard
async function runWizard() {
  clearScreen();

  // Welcome banner
  print();
  printBox([
    '                                          ',
    '   ██████╗  ██████╗ ██████╗ ██╗  ██╗      ',
    '   ██╔══██╗██╔═══██╗██╔══██╗██║ ██╔╝      ',
    '   ██║  ██║██║   ██║██████╔╝█████╔╝       ',
    '   ██║  ██║██║   ██║██╔══██╗██╔═██╗       ',
    '   ██████╔╝╚██████╔╝██║  ██║██║  ██╗      ',
    '   ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝      ',
    '            N E X U S                      ',
    '                                          ',
    '   Advanced Google Dorking Toolkit        ',
    '   Setup Wizard v1.0.0                    ',
    '                                          ',
  ], c.magenta);
  print();

  printColor(c.white, 'Welcome to DorkNexus! This wizard will help you set up');
  printColor(c.white, 'everything you need to get started.');
  print();

  const rl = createPrompt();

  try {
    // Step 1: System Check
    print();
    printColor(c.bright + c.white, '━━━ STEP 1: System Requirements ━━━');
    print();

    // Check Node.js
    const nodeCheck = checkNodeVersion();
    if (nodeCheck.ok) {
      printSuccess(`Node.js ${nodeCheck.version} detected`);
    } else {
      printError(`Node.js ${nodeCheck.version} detected (v18+ required)`);
      print();
      printColor(c.yellow, 'Please upgrade Node.js to version 18 or higher.');
      printColor(c.dim, 'Download from: https://nodejs.org/');
      rl.close();
      process.exit(1);
    }

    // Check npm
    const npmCheck = checkNpmInstalled();
    if (npmCheck.ok) {
      printSuccess(`npm ${npmCheck.version} detected`);
    } else {
      printError('npm not found');
      rl.close();
      process.exit(1);
    }

    // Check current state
    const depsInstalled = checkDependenciesInstalled();
    const envStatus = checkEnvConfigured();

    if (depsInstalled) {
      printSuccess('Dependencies already installed');
    } else {
      printWarning('Dependencies not yet installed');
    }

    if (envStatus.hasKey) {
      printSuccess('API key already configured');
    } else if (envStatus.exists) {
      printWarning('Environment file exists but API key not set');
    } else {
      printWarning('Environment file not configured');
    }

    print();
    await question(rl, `${c.dim}Press Enter to continue...${c.reset}`);

    // Step 2: Install Dependencies
    print();
    printColor(c.bright + c.white, '━━━ STEP 2: Install Dependencies ━━━');
    print();

    if (depsInstalled) {
      const reinstall = await confirm(rl, 'Dependencies are installed. Reinstall?', false);
      if (reinstall) {
        await installDependencies();
        printSuccess('Dependencies reinstalled successfully');
      } else {
        printSuccess('Skipping dependency installation');
      }
    } else {
      printColor(c.white, 'Installing required packages...');
      await installDependencies();
      print();
      printSuccess('Dependencies installed successfully');
    }

    // Step 3: Configure API Key
    print();
    printColor(c.bright + c.white, '━━━ STEP 3: Configure Gemini API Key ━━━');
    print();

    if (envStatus.hasKey) {
      const reconfigure = await confirm(rl, 'API key is configured. Reconfigure?', false);
      if (!reconfigure) {
        printSuccess('Keeping existing API key');
      } else {
        await configureApiKey(rl);
      }
    } else {
      await configureApiKey(rl);
    }

    // Step 4: Completion
    print();
    printColor(c.bright + c.white, '━━━ STEP 4: Setup Complete! ━━━');
    print();

    printBox([
      '                                    ',
      '  🎉 DorkNexus is ready to use!    ',
      '                                    ',
    ], c.green);

    print();
    printColor(c.white, 'Quick Commands:');
    print();
    printColor(c.cyan, '  npm run dev      ' + c.dim + '→ Start development server');
    printColor(c.cyan, '  npm run build    ' + c.dim + '→ Build for production');
    printColor(c.cyan, '  npm run preview  ' + c.dim + '→ Preview production build');
    print();

    // Offer to start the server
    print();
    const startNow = await confirm(rl, 'Would you like to start DorkNexus now?', true);

    rl.close();

    if (startNow) {
      print();
      printColor(c.green, '━'.repeat(50));
      printColor(c.bright + c.green, '  Starting DorkNexus...');
      printColor(c.green, '━'.repeat(50));
      print();
      printColor(c.white, '  Open your browser to: ' + c.cyan + c.bright + 'http://localhost:3000');
      printColor(c.dim, '  Press Ctrl+C to stop the server');
      print();
      startDevServer();
    } else {
      print();
      printColor(c.white, 'To start later, run: ' + c.cyan + 'npm run dev');
      print();
      printColor(c.dim, 'Thank you for choosing DorkNexus!');
      print();
    }

  } catch (error) {
    rl.close();
    print();
    printError(`Setup failed: ${error.message}`);
    process.exit(1);
  }
}

async function configureApiKey(rl) {
  print();
  printColor(c.white, 'You need a Google Gemini API key to use DorkNexus.');
  print();
  printColor(c.dim, 'Get your free API key at:');
  printColor(c.cyan, '  https://aistudio.google.com/apikey');
  print();

  let apiKey = '';
  while (!apiKey.trim()) {
    apiKey = await question(rl, `${c.yellow}Enter your Gemini API key: ${c.reset}`);
    if (!apiKey.trim()) {
      printWarning('API key cannot be empty');
    }
  }

  // Basic validation
  if (apiKey.length < 20) {
    printWarning('This API key looks short. Proceeding anyway...');
  }

  createEnvFile(apiKey.trim());
  printSuccess('API key saved to .env.local');
}

// Run the wizard
runWizard().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
